### ISSUE TITLE
SJSU-1023, Implement Redux for Individual Hotel Overview

### ISSUE THREAD

**Issue by SandroSal** [minhphan156/Abode#26]
As a React Component, I want to communicate with the backend, so I can get live, up to date data to display to the user.

Load data into component:
1) Use mapstateToProps to get result data from the reducer.
2) Use props to populate component

Please refer to wiki for details on which data will be received from backend & its naming convention:
https://github.com/minhphan156/Abode/wiki/Backend-to-Frontend-communication

**Comment by itjinshan** [comment]
Issue is completed. Please checkout SJSU-1023_ n (n can be 1, 2, 3, 4... ) for detail updates.
