### ISSUE TITLE
SJSU-1043, Update registration frontend

### ISSUE THREAD

**Issue by HongbinZheng** [minhphan156/Abode#89]
As a user, I want to be able to create an account and provide personal data, so I can enjoy a customized user experience later. (update 1000)

update the frontend of the registration, change the name to firstname and lastname. including update the redux

**Comment by DaleCS** [comment]
I don't understand. This feature had already been implemented and I already updated redux.

I did however took a look at validation and added some for the 'firstname' and 'lastname' field of the register component.
